### ISSUE TITLE
Unified logging everywhere

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#113]
1. Fix j.logger.log
2. Make sure it's being consistently used throughout the codebase

**Comment by zaibon** [comment]
Can we have nice colors too ?

**Comment by maxux** [comment]
For colors, you can use http://docs.fabfile.org/en/1.10/api/core/colors.html which is already part of Jumpscale :)

**Comment by zaibon** [comment]
Some documentation on how the new logging system works : https://gig.gitbooks.io/jumpscale8/content/Core/logging.html

**Comment by zaibon** [comment]
see #124
