### ISSUE TITLE
Fix monitoring JumpScripts

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#120]
Currently some jumpscripts don't work. Please investigate and fix.

**Comment by rkhamis** [comment]
Please make sure that the aggregation and tags are also all done.
Check with @muhamadazmy

**Comment by NourhanOmar** [comment]
The Jumpscripts are done for now where an aggregator client gets defined using a redis connection and the hostname of the node. The data being saved is tagged using the nid and gid. The keys are descriptive and are the actual data being saved in redis example: disks.space.used.mb or network.packets.send.
