### ISSUE TITLE
Unit Testing major modules

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#123]
TODO: Define modules to be tested

**Comment by zaibon** [comment]
- cuisine (mostly core)
-  AYS
- SSH client
- executors
These are IMO some critical modules we should take care of.

**Comment by rkhamis** [comment]
Maybe some of the more heavily used modules, like:
* HRD
* FS

**Comment by ahussein** [comment]
PR for cuisine unittests: https://github.com/Jumpscale/jumpscale_core8/pull/281
