### ISSUE TITLE
Cleanup redis client

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/jumpscale_core8#125]

**Comment by grimpy** [comment]
See https://github.com/Jumpscale/jumpscale_core8/pull/126
and https://github.com/Jumpscale/jumpscale_portal8/pull/41

**Comment by rkhamis** [comment]
@grimpy Maybe it would also be nice if you refactor the module name to not have an underscore or a 2?

**Comment by grimpy** [comment]
@rkhamis done
