### ISSUE TITLE
When too many ssh keys loaded in ssh-agent. Connection is refused from most of SSH servers.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jumpscale_core8#138]
Most of the ssh server won't accept more then x keys when trying to connect.
If the valid key is loaded in ssh-agent but not tried in time. connection will fail

**Comment by rkhamis** [comment]
This should be handled in the service loading the ssh-keys in my opinion. Shouldn't load too many/clean up old keys.

**Comment by grimpy** [comment]
Maybe just load 1 agent per service to prevent keys to build up?

**Comment by despiegk** [comment]
1 more comment to test

**Comment by rkhamis** [comment]
You can reproduce with using this blueprint: [https://github.com/gig-projects/playenv/tree/master/ays_fake]() 
(use ays from the ays_consume branch of core [https://github.com/Jumpscale/jumpscale_core8/tree/ays_consume]())
