### ISSUE TITLE
Move portal into j....cuisine.apps

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#145]

**Comment by despiegk** [comment]
???

**Comment by rkhamis** [comment]
The portal installation should be hooked under `j.tools.cuisine.apps.portal` instead of `j.tools.cuisine.portal` for easier code management and consistency

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/150
