### ISSUE TITLE
Use `j.exceptions` instead of `j.errorconditionhandler` everywhere

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#148]

**Comment by mie00** [comment]
Error handling in jumpscale

This is a proposal regarding exception in jumpscale:

1. Exceptions should be a subclass of our base exception class, they should have no side effects so they'll just contain data.

2. Exceptions should always be raised.

3. Warnings should has two parent classes oue base exception class and builtin `Warning`.

4. They should be used only to dump a warning to the stderr. they can be filtered or be raised an exception and they should follow [this](https://docs.python.org/3.3/library/warnings.html#module-warnings).

5. Logging of the exception and storing it in db shouldn't be the reponsiblity of the place where the exception occurs, instead it should be the responsibility of who handles it. ha can always find another way or log the exception and store it in the database.

6. If the exception is not handled it will propagate until it reaches our exception hook where he can always log the exception and store it in the database.

7. We can use j.logger.exception under an except statement to print the exception and it's traceback. see [here](https://docs.python.org/2/library/logging.html#logging.Logger.exception).

8. Exceptions should be serialized and stored in database.

9. Exceptions can have a serialize method to add custom attributes.

10. There is a namespace (eg. a class) to contain helpers regarding handling exceptions.

11. In this namespace there is a method to serialize exception objects and it should respect Exception.serialize method if it exists, and the output of this method is what will be stored in the database.

12. In this namespace there is a method to store the serialized object in the database to be used afterwords.

13. The two previous methods hould only be used in except statement where it gets the exception object from the `__context__` variable.

14. The exception class name should be part of what it shtored in the db.

15. The serialized data can be stored later on mongodb, so we can normally query them.

**Comment by muhamadazmy** [comment]
Proposal looks fine and matches what we discussed.

**Comment by despiegk** [comment]
you mention
5. Logging of the exception and storing it in db shouldn't be the reponsiblity of the place where the exception occurs, instead it should be the responsibility of who handles it. ha can always find another way or log the exception and store it in the database.

could be dangerous, what if people do not process it?
with db do you mean redis or something else?

WANT TO MAKE SURE
- we never lose track of an error happening

**Comment by mie00** [comment]
Handling an exception using except statement gives you full responsibility of the exception, that includes logging and storing or even reraising it depending on the situation, so normally none of that will happen automatically if you catch it. 

If the exception is not handled manually , it will be handled using a custom excepthook, and it will always log and store it. 

Storing exceptions means storing them temporarily in a redis server, and they get moved later to mongo, and in mongo they can be aggregated and analyzed.

**Comment by rkhamis** [comment]
Don't forget the portal repo as well

**Comment by rkhamis** [comment]
Moved to https://github.com/Jumpscale/portal9/issues/3
