### ISSUE TITLE
cuisine wrong fix

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#173]
![image](https://cloud.githubusercontent.com/assets/6021844/14578952/63322fa2-0399-11e6-8470-e8a2e55a4bcd.png)

sure this will not work

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/172, this is on  a branch not merged yet , the fix was adjusted , apologies
