### ISSUE TITLE
Install script tries to retrieve non-existing script

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_core8#180]
In the install script https://github.com/Jumpscale/jumpscale_core8/blob/master/install/install.sh#L88 the code tries to download a helper script that does not exist in the same location anymore in the repo.

file url in script: https://raw.githubusercontent.com/Jumpscale/jumpscale_core8/master/install/web/InstallTools.py

file url in the repo: https://raw.githubusercontent.com/Jumpscale/jumpscale_core8/master/install/InstallTools.py

Another the problem is that the install script does not fail when the command fails.

**Comment by despiegk** [comment]
is this still issue?
if yes please fix & create pull request
