### ISSUE TITLE
Email SAL

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#185]
- check sal in jumpscale to
- process the emails (mime format)
- create sal to access the redis email info
- check sal to write email

check https://github.com/gig-projects/org_development/issues/4 for more information

**Comment by muhamadazmy** [comment]
Reference to the mandrill webhook.
https://github.com/Jumpscale/jumpscale_portal8/commit/32a1417548f121a17842d0e5f17fb620e74fee72

The sal should implemente the following methods
```python
getLast(num=10): #gets latest num emails (no pop)
pop(): #pops the oldest email out of the queue (also removes it from the hset)

#both getLast, and pop should return instance of `Email` which has attributes to expose
#meta data. also method to load content from the HD.
#example
class Email():
   @property
    def sender(self):
         #return sender.
   
   def content():
        # loads content from hard-disk

   #same for attachment access
```

**Comment by muhamadazmy** [comment]
Docs for the message structure
https://mandrill.zendesk.com/hc/en-us/articles/205583207-What-is-the-format-of-inbound-email-webhooks-

**Comment by muhamadazmy** [comment]
I finished the email sending part, it uses smtp to send emails and can work against mandrill smtp interface

**Comment by xmonader** [comment]
Okay, I got the message wrapper and documented it. and add context manager to the Sender as well
