### ISSUE TITLE
sal.ubuntu checkroot fails

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/jumpscale_core8#186]
```python
    @property
    def whoami(self):
        rc,result=self._local.execute("whoami")
        return result.strip()
    def checkroot(self):
        if self.whoami() != "root": #calling the property whoami...
            j.events.inputerror_critical("only support root")
```

suggested fixes:
1- remove @property decorator from the whoami definition
2- remove the self.whoami method call and access the whoami property

Isn't it supposed to return True if root and False if otherwise? it returns None if self.whoami == 'root'

**Comment by abdulrahmantkhalifa** [comment]
different implementation of fixes choose reviewer chose one
