### ISSUE TITLE
sal/fs isExecutable is broken if not executable by the owner, but executable by others

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/jumpscale_core8#195]
sal.fs.isExecutable expects that file is only executable if and only if the user got x permissions
but what if the file was executable by others?

```python
    def isExecutable(self, path):
        statobj=self.statPath(path)
        return not (stat.S_IXUSR & statobj.st_mode==0)

```

I think we should check against S_IXOTH and S_IXGRP as well.

**Comment by despiegk** [comment]
far fetched, prob not needed to fix now
so wont fix
