### ISSUE TITLE
github client: github style list of tasks instead of markdown table

### ISSUE THREAD

**Issue by robvanmieghem** [Jumpscale/jumpscale_core8#213]
Currently the stories are updated with a list of tasks in a markdown table.
It would be better to use the github `- [ ]` style of tasks lists since it better integrates with the rest of the github toolset like the issues list:
<img width="732" alt="screen shot 2016-05-10 at 10 52 54" src="https://cloud.githubusercontent.com/assets/3511318/15141104/cb029c44-169e-11e6-8e72-36d7fc90de14.png">

**Comment by rkhamis** [comment]
This shouldn't be reported here. But in https://github.com/Jumpscale/github_automation/issues.
Will move.
