### ISSUE TITLE
etcd and caddy do not run properly when run from cuisine 

### ISSUE THREAD

**Issue by abdulrahmantkhalifa** [Jumpscale/jumpscale_core8#216]
## goal
-fix both so they run properly 

## comments  
discription (for etcd):
no error will appear but the process halts directly afterwards ;
in docker ```sv etcd status``` always appears to be down which is what cuisine uses as the process manager , although , when the command is  run from bash directly ```etcd``` runs normally. 

to build and start :
```
j.tool.cuisine.local.apps.etcd.build(start=True)
```

**Comment by abdulrahmantkhalifa** [comment]
commit on branch issue_216

**Comment by rkhamis** [comment]
@abdulrahmantkhalifa could you explain more what goes wrong?

**Comment by abdulrahmantkhalifa** [comment]
i believe this is done closed , tested
