### ISSUE TITLE
ActionDecorator unittest fails

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_core8#257]
First attempt to write unittests for JumpScale.tools.cuisine.ActionDecorator showed a bug when passing action flag as False
check the test case in https://github.com/Jumpscale/jumpscale_core8/blob/tools_unittests/tests/tools/cuisine/TestActionDecorator.py

result of running the tests:

```
root@697e6b49fda1:/opt/jumpscale8# nosetests tests/
E.
======================================================================
ERROR: Test call a decorated action
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/jumpscale8/tests/tools/cuisine/TestActionDecorator.py", line 51, in test_call_actoindecorator
    action()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/ActionDecorator.py", line 20, in wrapper
    cuisine=args[0].cuisine
IndexError: tuple index out of range

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)
root@697e6b49fda1:/opt/jumpscale8# 
```

if the action flag is set to False then the code should not expect there will be an cuisine object in the argument list of the function.

**Comment by mie00** [comment]
The action decorator was intended for instances where they have cuisine as attribute, so the first argument will be self and hence `args[0].cuisine` will work.
So for testing you can make an object with that has cuisine as an attribute and call action with it as a first argument.

**Comment by ahussein** [comment]
This does not make any sense. if the action flag is set to false then the cuisine instance is not used at all and the decorated function is supposed to be executed normally. this behavior is not implemented correctly, this is a unittest not a functional or integration test, the test does not make any hidden assumption.
The code needs to be fixed, either to handle the action flag set to false and then do not fail if there is not arg[0] or remove that flag all together. Just do not leave code that is non-functional.

**Comment by mie00** [comment]
Even if you set action to `True` the same error will appear. Simply because it is used in a wrong way.
Normally - by setting action to `True` - it requires the first argument to be an object that contains cuisine, and that's why it won't work in your case. And that is why setting it to `False` doesn't justify using it in a wrong way.

**Comment by ahussein** [comment]
check the unittests again: https://github.com/Jumpscale/jumpscale_core8/blob/tools_unittests/tests/tools/cuisine/TestActionDecorator.py

I added a testcase where action is true and an executor is passed since its needed
another testcase where action is false and no executor is passed since its not needed and not used when action flag is false

The code should not assume the intention when it was written. The code need to be explicit, If the intention is not to allow executing any action without an executor that is fine, but the code need to explicit raise a proper exception and error message in this case, a tuple out of index exception is not acceptable since its programming error and not an application error.
