### ISSUE TITLE
j.tools.expect is broken for windows

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/jumpscale_core8#298]
At first glance, it looked like tab/spaces and subprocess.mswindows missing attribute problem, but it turned to be bit complex. 
There's no pxssh , no j.logger.addConsoleLogger  and it affects tools/admin/Node, shellcmds/jsdesktop

**Comment by despiegk** [comment]
does it work when we install in unix tools on windows?

**Comment by rkhamis** [comment]
No longer an issue with js9 docker
