### ISSUE TITLE
j.sal.netconfig is broken

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/jumpscale_core8#301]
1- No logger
2- usage of undeclared variables (devToApplyTo for instance) 
3- usage of unknown functions/methods (ureset, self.interfaces_apply, self.shutdownNetwork, self.resetDefaultGateway, self.getDefaultIPConfig, self.bridgeExists, self.reset, self.removeNetworkFromInterfaces, enableInterface, enableInterfaceBridgeStatic, setRoot, setNameServer 

There are some fixes in this branch https://github.com/Jumpscale/jumpscale_core8/tree/fixesfor301

**Comment by despiegk** [comment]
@xmonader what is status here, still relevant, if yes please specify what needs to be done

**Comment by xmonader** [comment]
Fixed on master now.
