### ISSUE TITLE
Jumpscale should also be usable on a constrained user -- not root

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/jumpscale_core8#306]
Currently things like the jumpscale portal backend needs to run with root. This makes the portal insecure by default why issues like the following keep popping up:  https://github.com/0-complexity/openvcloud/issues/195

**Comment by despiegk** [comment]
for now we can run it in a docker which can't do anything

**Comment by rkhamis** [comment]
Not relevant for js9
