### ISSUE TITLE
PEP8 codebase

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#310]
## GOAL:
Code readability and standardization

## DESCRIPTION:
There's an autopep8 tool available in pypi (install with `pip3 install autopep8`)
I propose maximum line length to be 120 characters. 

 1. Run`autopep8 . --recursive --in-place --verbose --max-line-length=120 `
 2. Change all `== False` to `is False` (`is` is a stronger operand, comparing that it's one and the same object, not just the same value)
 3. Rebase all branches to prevent merge conflicts

We should also have a post-commit hook to keep the codebase clean.
This would run after each commit, autopep8 the changes and commit them.
Something like this:
```
#!/bin/sh

FILES=$(git diff HEAD^ HEAD --name-only --diff-filter=ACM | grep -e '\.py$')
 
for f in $FILES
do
    autopep8 $f --in-place  --verbose --max-line-length=120
done
```

Eventually, method and variable names should also be refactored to be pep8 compliant.

**Comment by despiegk** [comment]
done

**Comment by khaledkbadr** [comment]
https://github.com/0-complexity/tutorials/blob/master/7_autopep8/1_install.md
