### ISSUE TITLE
Documentation does not specify how to put the jumpscale sandbox in debug modus.

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/jumpscale_core8#347]

**Comment by yveskerwyn** [comment]
@rkhamis after having installed **JumpScale in a sandbox** as documented [here](https://gig.gitbooks.io/jumpscale-core8/content/Installation/JS8.html) I'm a bit lost...

I was expecting that I could at least use ```js``` but I get this:

```
root@vm-45:/tmp# js
The program 'js' can be found in the following packages:
 * nodejs
 * rhino
Try: apt install <selected package>
```

Is this normal? Am I missing something?

**Comment by despiegk** [comment]
@yves what has this comment to do with issue?

**Comment by yveskerwyn** [comment]
@despiegk it is indeed not directly related, only indirectly: the current documentation doesn't specify anything on how exactly "JumpScale in a sandbox" can be used, let alone how to put it in "debug" mode...

As a first step to solve that issue I first installed JumpScale in a sandbox as documented [here](https://gig.gitbooks.io/jumpscale-core8/content/Installation/JS8.html), I was now simply wondering why executing `js` resulted in the above mention error message...

Anyway, I've created a new issue to file this as a bug: [#632](https://github.com/Jumpscale/jumpscale_core8/issues/632)
