### ISSUE TITLE
AYS to use capnp schema's

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#454]
translate an hrd schema like
![image](https://cloud.githubusercontent.com/assets/6021844/17296484/c97222ce-5801-11e6-9b2a-b4093fab557b.png)

to capnp schema

![image](https://cloud.githubusercontent.com/assets/6021844/17296492/d3866a2c-5801-11e6-817c-5c3d8293c536.png)

**Comment by xmonader** [comment]
Here's an example of initial support for types(str, int, list, bool, float)
```

In [1]: schema="""                             
name = type:str
age  = type:int\n users = type:str list\nfat=type:bool\npi=type:float"""

In [2]: sc=j.data.hrd.getSchema(content=schema)

In [3]: sc.asCapnpSchema()                
Out[3]: '\n\n@yk2gfqmfsiy854uhsz3u ;\n\nstruct schema{\n\n\tname @0 :Text;\n\tage @1 :UInt32;\n\tusers @2 :List(Text);\n\tfat @3 :Bool;\n\tpi @4 :Float32;\n\n\n}\n\n        '

In [4]: print(sc.asCapnpSchema())


@l5zf2x7f72dy1rlqzpib ;

struct schema{

        name @0 :Text;
        age @1 :UInt32;
        users @2 :List(Text);
        fat @3 :Bool;
        pi @4 :Float32;


}

```
via #456

**Comment by zaibon** [comment]
I fixed and improve the schema generator. 
- ID is now generated from the capnp CLI tool
- Stuct name is capitalized
- Make sure field name have valid format
https://github.com/Jumpscale/jumpscale_core8/commit/04170d61c6918c8dfdcbbfbef6308a3ca3e6fb4c
