### ISSUE TITLE
need a method to execute our testcases from the cockpit blue print 

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jumpscale_core8#473]
**Description**
We need to connect from the cockpit to a physical node, git our testing repo, execute test cases then send the output to mails and telegram channels.

**Goal**
According to this task https://github.com/gig-projects/org_quality/issues/370
We need an AYS service which will handle a blueprint with the following specs:

- Destination physical node like du-conv-2-master
- Bash script which will be executed in the physical node
- Mails to send the output result to it
- Telegram channel to send the output result to it

**Comment by hofkensj** [comment]
In my view masters Connect to physical nodes and cockpit manage user loads - so i would rather have the master provider the facility and a cockpit with the right access rights to use it.  Otherwise we create a security hole.

**Comment by islamTaha12** [comment]
We have to configure the cockpit docker to be able to connect the nodes by adding the ssh keys config so I think there is no security hole unless the attacker own the cockpit machine or the config ssh key.

**Comment by ramezsaeed** [comment]
We need this to test the cloud api calls which are only callable from the nodes.

**Comment by yveskerwyn** [comment]
@ramezsaeed Can't it be done through Agent/AgentController?

**Comment by rkhamis** [comment]
After discussion with @ramezsaeed , this feature is unneeded.
