### ISSUE TITLE
improve SAL for KVM   / openvswitch

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#510]
- add support for openvswitch (in stead of std bridge)
    - multiple nics per vm
    - will require mods to openvswitch sal, please also doc better
- multiple disks to vm
- add support for QOS
    - iops on vdisk
    - througput on nics
- create good documentation in js8 docs (gitbook)
- implement import/export method
- following images all hosted on ftp/http server (compress using very good lib)
    - absolute minimal ub 16.04
    - ub 16.04 std: mc, curl, python3.5... all minimal requirements for js8 & docker pre-installed
    - openwrt (newest version)
- implement as 3 classes, each class has appropriate props & methods e.g. start, stop, export, ...
   always work against reality !!!
    - vmachine
    - vnic
    - vdisk
- implement an NFS boot method
    - start local nfs server
    - create btrfs fs for disk e.g. /mnt/vmstor/$vmname/vfs_$diskname
    - boot linux with smalles possible boot image (ISO?)
    - then mount over nfs & further boot from btrfs filesystem over nfs? (better alternative than nfs?)
    - test this for the 3 images above (where they get expanded in  /mnt/vmstor/vfs_templates/$name and then we clone them to appropriate location to boot from)
     - this will allow us later to use our G8OS FS as backend for KVM as well & faster testing

**Comment by rkhamis** [comment]
Implemented without the NFS part. Moving that to: https://github.com/Jumpscale/jumpscale_core8/issues/534
