### ISSUE TITLE
fix/improve introspection/doc generator tool

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#514]
to get info out of jumpscale & generate .md docs

- document this in js8 docs
- the interface is confusing, doc better & improve
- test on full js8

**Comment by xmonader** [comment]
I made some improvements on objectinspector and generated the the complete docs of j
![screenshot from 2016-08-28 16-27-26](https://cloud.githubusercontent.com/assets/64129/18034402/ca729728-6d44-11e6-8499-d005179e1f15.png)

**Comment by rkhamis** [comment]
@despiegk is this output okay?
@xmonader I'd prefer "comments" not to be there, personally. Directly show the docstring.

**Comment by despiegk** [comment]
where is docu for this?

**Comment by xmonader** [comment]
Documentation can be generated using this

```
j.tools.objectinspector.generateDocs(dest="/tmp/") 
```
It's generated under docs/JumpscaleAPI in gitbook format
https://github.com/Jumpscale/jumpscale_core8/tree/master/docs/JumpscaleAPI
