### ISSUE TITLE
Cuisine upload fails locally

### ISSUE THREAD

**Issue by maxux** [Jumpscale/jumpscale_core8#520]
`CuisineCore: upload` uses `self._executor.sshclient.rsync_up(source, dest)` to upload files.
This is not implemented when cuisine is used with locally (`j.tools.cuisine.local`).

**Comment by rkhamis** [comment]
https://github.com/Jumpscale/jumpscale_core8/commit/592222b8118c671cd977caec02a9eaf4241f71f8#diff-1f63ff5a15181c885c31ce0b896b57bd
