### ISSUE TITLE
Not all dependencies are there after the installation of js8

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jumpscale_core8#522]
After going through the installation of js8 --> https://github.com/Jumpscale/jumpscale_core8/blob/master/docs/GettingStarted/Installation.md, there was some missing dependencies like paramiko

hint: we need to run -- >  "j.tools.cuisine.local.development.js8.installDeps() "  to install dependencies .. not sure if there is another thing missing.

**Comment by khaledkbadr** [comment]
Yeah, dependencies are no longer installed with the installation of JS. They must be installed explicitly.

**Comment by yveskerwyn** [comment]
It would be useful to have a list in the documentation of all the dependencies, do we have that?

**Comment by khaledkbadr** [comment]
@yveskerwyn I don't think so

**Comment by abdulrahmantkhalifa** [comment]
js8.0.beta branch  added to the documentation

**Comment by rkhamis** [comment]
The idea here is to not install every possible needed dependency by default.
