### ISSUE TITLE
js801: test gogs client [1.5d]

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#526]
/opt/code/github/jumpscale/jumpscale_core8/lib/JumpScale/clients/gogs/GogsClient.py

implement

```
    def test(self):
        # compile gogs (using cuisine golang, ...)
        # start gogs using process manager j.core.... in subprocess
        # create orgs
        # create users
        # list orgs/users
        # create issues
        # list issues
        # delete issues
        # delete users
        # delete orgs
```

is in the client

**Comment by despiegk** [comment]
i think most of this already works, lets just test

**Comment by despiegk** [comment]
just needs to be closed & verified, is needed to automate our process which is urgent

**Comment by xmonader** [comment]
Client is working against latest gogs 
https://github.com/Jumpscale/jumpscale_core8/commit/35c3fb67b04135522a85936fb39b309efb94a3e9https://github.com/Jumpscale/jumpscale_core8/commit/35c3fb67b04135522a85936fb39b309efb94a3e9

CuisineGogs is responsible for building/installing gogs and applying itsyouonline integration (currently there's an issue with tmux processmanager but the command it runs works fine)
https://github.com/Jumpscale/jumpscale_core8/commit/0a992c9ef6dff03b05aa3e266836c3ca72e1ce48
