### ISSUE TITLE
Install fails when installing CAPNP

### ISSUE THREAD

**Issue by hofkensj** [Jumpscale/jumpscale_core8#531]

**Comment by hofkensj** [comment]
creating /tmp/tmpeg96bxju/tmp
cc -c /tmp/timer_createp14c4265.c -o /tmp/tmpeg96bxju/tmp/timer_createp14c4265.o
/tmp/timer_createp14c4265.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
main (int argc, char **argv) {
^
/tmp/timer_createp14c4265.c: In function ‘main’:
/tmp/timer_createp14c4265.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
timer_create();
^
cc /tmp/tmpeg96bxju/tmp/timer_createp14c4265.o -o /tmp/tmpeg96bxju/a.out
/tmp/tmpeg96bxju/tmp/timer_createp14c4265.o: In function `main':
timer_createp14c4265.c:(.text+0x15): undefined reference to `timer_create'
collect2: error: ld returned 1 exit status
creating tmp
creating tmp/tmpeg96bxju
cc -c /tmp/tmpeg96bxju/vers.cpp -o tmp/tmpeg96bxju/vers.o --std=c++11
/tmp/tmpeg96bxju/vers.cpp:4:26: fatal error: capnp/common.h: No such file or directory
compilation terminated.
*WARNING* no libcapnp detected. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
fetching https://capnproto.org/capnproto-c++-0.5.2.tar.gz into /tmp/pip-build-dd1pv2f7/pycapnp/bundled
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make: *** [src/capnp/compiler/capnpc-c++.o] Error 4
make: *** Waiting for unfinished jobs....
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-dd1pv2f7/pycapnp/setup.py", line 176, in <module>
'Topic :: Communications'],
File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
self.run_command(cmd)
File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
cmd_obj.run()
File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 179, in run
self.run_command('build')
File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
cmd_obj.run()
File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
self.run_command(cmd_name)
File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
cmd_obj.run()
File "/tmp/pip-build-dd1pv2f7/pycapnp/setup.py", line 120, in run
build_libcapnp(bundle_dir, build_dir)
File "/tmp/pip-build-dd1pv2f7/pycapnp/buildutils/build.py", line 30, in build_libcapnp
raise RuntimeError('Make failed')
RuntimeError: Make failed

----------------------------------------
Running setup.py clean for pycapnp
Failed to build pycapnp
Installing collected packages: pycapnp
Running setup.py install for pycapnp: started
Running setup.py install for pycapnp: finished with status 'error'
Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dd1pv2f7/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-67hup9ko-record/install-record.txt --single-version-externally-managed --compile:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-dd1pv2f7/pycapnp/setup.py", line 92, in <module>
from Cython.Distutils import build_ext as build_ext_c
ImportError: No module named 'Cython'

----------------------------------------
Failed building wheel for pycapnp
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dd1pv2f7/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-67hup9ko-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-dd1pv2f7/pycapnp/
Traceback (most recent call last):
  File "bootstrap.py", line 59, in <module>
    do.installer.prepare()
  File "/tmp/InstallTools.py", line 2480, in prepare
    do.executeCmds(cmds)
  File "/tmp/InstallTools.py", line 997, in executeCmds
    rc, out, err = self.execute(cmd, showout, outputStderr, useShell, log, cwd, timeout, captureout, die)
  File "/tmp/InstallTools.py", line 1114, in execute
    raise RuntimeError("Could not execute cmd:\n'%s'\nerr:\n%s" % (command, err))
RuntimeError: Could not execute cmd:
'pip3 install pycapnp'
err:
Failed building wheel for pycapnp
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dd1pv2f7/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-67hup9ko-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-dd1pv2f7/pycapnp/

**Comment by despiegk** [comment]
can we reproduce? what is the issue?

**Comment by rkhamis** [comment]
@hofkensj Which install fails? JumpScale?

**Comment by rkhamis** [comment]
@hofkensj JumpScale installs fine. So does Capnp through cuisine.

**Comment by hofkensj** [comment]
Did a reinstall - working now -

Jurgen

**Comment by maorros** [comment]
I have the same problem. 
Can you elaborate on how you reinstalled?

**Comment by rkhamis** [comment]
@maorros you probably are missing some deps.
Try 
```
apt-get install build-essential python3-dev libssl-dev -y
pip3 install Cython
pip3 install pycapnp
```

**Comment by maorros** [comment]
The following has solved the problem:
sudo pip install --install-option '--force-bundled-libcapnp' pycapnp

I'm using python2.7, but thanks for the response!
