### ISSUE TITLE
Add NFS boot for KVM SAL

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#534]
- implement an NFS boot method
  - start local nfs server
  - create btrfs fs for disk e.g. /mnt/vmstor/$vmname/vfs_$diskname
  - boot linux with smalles possible boot image (ISO?)
  - then mount over nfs & further boot from btrfs filesystem over nfs? (better alternative than nfs?)
  - test this for the 3 images above (where they get expanded in  /mnt/vmstor/vfs_templates/$name and then we clone them to appropriate location to boot from)
    - this will allow us later to use our G8OS FS as backend for KVM as well & faster testing

**Comment by despiegk** [comment]
wont do
