### ISSUE TITLE
When installating JS on Ubuntu 16.04: locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#537]
...

Setting up manpages-dev (4.04-2) ...
Setting up python-pip-whl (8.1.1-2ubuntu0.2) ...
Setting up python3-colorama (0.3.7-1) ...
Setting up python3-click (6.2-2ubuntu1) ...
Setting up python3.5-dev (3.5.2-2~16.04) ...
Setting up python3-dev (3.5.1-3) ...
Setting up python3-pip (8.1.1-2ubuntu0.2) ...
Setting up python3-setuptools (20.7.0-1) ...
Setting up python3-wheel (0.29.0-1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
+ pip3 install --upgrade uvloop
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by yveskerwyn** [comment]
During installation I always see following:
...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
...

**Comment by yveskerwyn** [comment]
And even if I ignore all this, and try to run JS at the end of the installation I get this:

root@vm-18418:/tmp# js
The program 'js' can be found in the following packages:
 * nodejs
 * rhino
Try: apt install <selected package>

@despiegk @rkhamis @zaibon please help, since this issue is already open since 14 days without any reaction!!

**Comment by rkhamis** [comment]
Checked again. Works perfectly fine on a fresh ubuntu 16.04.
Used this guide to install https://gig.gitbooks.io/jumpscale-core8/content/Installation/JSDevelopment.html

**Comment by rkhamis** [comment]
Will check on be-g8-4 as well

**Comment by rkhamis** [comment]
checked. works.

**Comment by yveskerwyn** [comment]
Didn't have this problem/warning on VirtualBox, only difference was that I executed `locale-gen` prior to installing JS

When doing the exact same thing on be-g8-4 installation ended with:

```
Setting up python3-wheel (0.29.0-1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
+ pip3 install --upgrade uvloop
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
Will try once more on be-g8-4
