### ISSUE TITLE
docu ays81 portal

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#541]
- create documentation how to
  - start portal (just starting from std js8 libraries)
  - use the portal to see ays repo's

**Comment by yveskerwyn** [comment]
@khaledkbadr Khaled thanks for pointing me to the documentation?

**Comment by khaledkbadr** [comment]
https://github.com/Jumpscale/jumpscale_portal8/blob/master/docs/GettingStarted/Running.md
