### ISSUE TITLE
Ays repoList returns incremental redundant values

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/jumpscale_core8#544]
when running `j.atyourservice.reposList` if you have an ays repo that has any capital letter in its path for example: `G` in `/opt/code/github/0-complexity/G8_testing/ays_testing/ays_qa_tests`
It'll always add new repo each time it runs

**Comment by zaibon** [comment]
fixed in ays81 branch. Problem was the key of model in database was always lowered:
https://github.com/Jumpscale/jumpscale_core8/commit/2445caa81e717051bedb0228a87807560d097a12#diff-b41d6a49b040bb4d389f84ff118ed60fR57
