### ISSUE TITLE
reposList retain repos even after removing .ays file

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/jumpscale_core8#546]
When I have ays repo and execute `j.atyourservice.reposDiscover` then `j.atyourservice.reposList` contain that repo (which is good).

Problem is when I remove `.ays` file from that repo and execute `j.atyourservice.reposDiscover` then `j.atyourservice.reposList` still contain that repo (which is not right).

I think it checks the repo path only which exists of course but that's not an ays repo anymore

**Comment by zaibon** [comment]
the `ays discover` command is just to discover existing repositories and saved them in the database.
removing the .ays file doesn't remove anything from the database so it's normal the repo is still shown by `ays repo_list`. If you want to delete a repository, use `ays destroy` when you're in this repo.

**Comment by rkhamis** [comment]
This is by design... You only scan your local filesystem. To later on be distributed, we cannot have reposDiscover remove repo models it doesn't find while scanning.
