### ISSUE TITLE
Minimize InstallTools

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#548]
Currently executor is too advanced for an installer. It should be doing just enough to bootstrap jumpscale.

if more advanced executor is needed elsewhere in the code, it should be developed on j....process.execute and used from there

**Comment by despiegk** [comment]
put on roadmap not urgent now

**Comment by despiegk** [comment]
see also #576

**Comment by rkhamis** [comment]
Covered in https://github.com/Jumpscale/core9/issues/3
