### ISSUE TITLE
FileNotFoundError when executing ays blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#552]
When executing ays blueprint:

FileNotFoundError: [Errno 2] No such file or directory: '/optvar/cfg/ays/ays.conf'

And indeed in /optvar/cfg/ays there is no **ays.conf**, only a **ays.config** exists

Renaming the file seems to solve this problem...

**Comment by rkhamis** [comment]
Fixed as well
