### ISSUE TITLE
Installing JS8 (master) seems to hang on pycapnp

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#555]
Waiting already 10 minutes:
...
Successfully installed cython-0.25.1
Collecting pycapnp
  Downloading pycapnp-0.5.9.tar.gz (455kB)
    100% |████████████████████████████████| 460kB 1.6MB/s
Building wheels for collected packages: pycapnp
  Running setup.py bdist_wheel for pycapnp ... |

**Comment by xmonader** [comment]
Does your machine fit the min requirements?
Because the pycapnp part eats up resources

**Comment by yveskerwyn** [comment]
I think indeed that this is the problem, thanks @xmonader
