### ISSUE TITLE
JumpScale should search for redis connection defined in its config and not hardcoded value

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jumpscale_core8#556]
During the bootstrap of jumpscale, it looks for a redis socket at ` $tmpdir/redis.sock`. I think instead of using hardoded value it should look in the configuration and use the value defined there.

code that check the existence of the socket: 
https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/clients/redis/RedisFactory.py#L50

**Comment by despiegk** [comment]
please, JS should work without any configuration, I find it wrong practice that for jumpscale config files should be a must.

- There is nothing wrong by having some defaults, proper usage of env variables 
- Personally I dislike config files especially at bootstrap this can give issues quickly

lets define what we want & then fix once we all agree

**Comment by rkhamis** [comment]
Current scenario:
Installation writes bare-minimum config files:
 - system:
```
 dirs:
     CFGDIR: /optvar/cfg/
     CODEDIR: /opt/code/
     DATADIR: /optvar/data/
     JSBASE: /opt/jumpscale8/
     TMPDIR: /tmp/
     VARDIR: /optvar/
 identity:
     EMAIL: ''
     FULLNAME: ''
     GITHUBUSER: ''
 system:
     AYSBRANCH: master
     DEBUG: false
     JSBRANCH: master
     SANDBOX: false
```
- AYS:
```
metadata:
    jumpscale:
        url: https://github.com/Jumpscale/ays_jumpscale8
        branch: master
```

- logging:
```
mode: 'DEV'
level: 'DEBUG'

filter:
    - 'j.sal.fs'
    - 'j.data.hrd'
    - 'j.application'
```


I prefer keeping the usage of env variables only during installation to minimize user errors. But let's discuss before deciding anything.

**Comment by despiegk** [comment]
Lets put state on question
