### ISSUE TITLE
producers of a service are not computed properly

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#566]
Expect behavior is:
 - if a consumption is set in the blueprint, _init_producers should link that service.
 - if it's not set in the blueprint and in the actor schema.hrd:
     - if the minimum is 0, do nothing
     - if minimum > 0:
         - if `auto` is not set, _init_producers should NOT link.
         - if `auto` is set, _init_producers should try to find an existing candidate
             - if a candidate already exists and is not ITSELF, link
             - if no candidate exists, create as many as the `minimum` set on the schema.hrd

**Comment by john-kheir** [comment]
Verified on 8.1.0 rc1
