### ISSUE TITLE
CuisineCockpit doesn't create config file during installation.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jumpscale_core8#567]
The install method of the CuisineCockpit module doesn't create the configuration file required by the AYS API.

**Comment by despiegk** [comment]
I believe every tool inside JS should be able to be used without configuration file as a default.
Lets discuss

**Comment by zaibon** [comment]
Nearly every cuisine module creates configuration when installed.
I agree tools should have default value to be ready to use out of the box. 
But since cuisine is used by AYS to do everything, we need to have these method in Cuisine so we don't put logic in the AYS templates.

**Comment by despiegk** [comment]
Lets not forget behavior in g8os fs is different so we need to prepare for
it

**Comment by zaibon** [comment]
Then shouldn't this be put for 8.2.0 ?

**Comment by despiegk** [comment]
was 10 min work, we spent more time arguing about it
