### ISSUE TITLE
cuisine should not do caching & default should not call dependencies

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#576]
suggest the following approach

- for each method which installs a full product, add argument: dependencies=False
    - if dependencies=True then deploy dependencies
- it's ok to check if dependency was physically deployed on node & then skip but never use caching or some metadata
- make sure we NEVER install dependencies in a method unless if dependencies=True arg used

**Comment by zaibon** [comment]
I don't really like the `just add a argument to everything` that completely change the behavior of the function.
We should have small function that do one thing. So in this case, normal install method that only install the application. one method that install the dependencies if any. and one method that do both with an explicit name.

each function has its own purpose and we don't completely change the function method by change an argument.

**Comment by despiegk** [comment]
I dont think this will do
People who want to use cuisine to install something should have a
convenience way. They dont know all requirements

**Comment by zaibon** [comment]
> People who want to use cuisine to install something should have a
convenience way. 

I agree that's why I propose to have a method that does the all-in one but this should not be the plain `install` method. it should have a name that explicitly says that a lot of thing will happens.

**Comment by rkhamis** [comment]
I'd prefer we do the building/installation/configuration in AYS services and keep Cuisine only for core components that provide a development added value.

**Comment by despiegk** [comment]
Ah ok makes sense

**Comment by despiegk** [comment]
think resolved in 8.2.0 there is a .done...feature on each cuisine class can be used
