### ISSUE TITLE
agree/doc testing strategy for jumpscale related repo's

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#578]
some options
* unit tests in python using python tools
* .test() method on right libs e.g. j.atyourservice.test()
* ays driven tests (can be combined with above)

we all need to agree & document in our procedures, this needs to be discussed by team
- we then need to make sure everyone will agree with this
- document in https://github.com/Incubaid/dev_process

**Comment by zaibon** [comment]
> unit tests in python using python tools

This should not be an option but a common practice used during development. Proper unit test is also a self-documenting way to show how to use a piece of code.

> .test() method on right libs e.g. j.atyourservice.test()

I'm against that. it pollute the public interface of the module. 

> ays driven tests (can be combined with above)

Good for bigger test (integration, validation)
Should also be possible to run all the unit tests in on go.

**Comment by rkhamis** [comment]
> ays driven tests (can be combined with above)

We're already working on this https://github.com/gig-projects/org_development/issues/1223 and https://github.com/gig-projects/org_development/issues/1144
These should already give us a huge push in integration testing.


> unit tests in python using python tools

I agree that we should make this an integral part of development.

**Comment by rkhamis** [comment]
https://github.com/Jumpscale/home/issues/11
