### ISSUE TITLE
agree/doc how we will do specifications & plan work

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#579]
review following suggestion
* suggest https://github.com/Incubaid/dev_process/blob/master/specs.md 

cleanup
- we need to go over all open stories & create FR & specs in the repos

we all need to agree & document in our procedures, this needs to be discussed by team
- we then need to make sure everyone will agree with this
- document in https://github.com/Incubaid/dev_process

**Comment by despiegk** [comment]
master/tests/tools/cuisine/TestCuisineBuilder.py

**Comment by despiegk** [comment]
- [TestCuisineBuilder.py](../blob/master/tests/tools/cuisine/)

**Comment by despiegk** [comment]
[e](Incubaid/dev_process/blob/master/specs.md

**Comment by rkhamis** [comment]
@FastGeert, @despiegk done? I think it's all documented
