### ISSUE TITLE
AYS support many more ays repo's & need to be easy

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#581]
- suggestion is to have no longer separate AYS template repo's but consider AYS templates to be part of product which AYS is automating
    - e.g. AYS to do with portal are in portal repo
- this requires AYS to be more flexible and should be more easy to use multiple ays template repo's

**Comment by zaibon** [comment]
Can we imagine a global registry that list all available templates, and user can just pick from it. Then automaticly these templates would be made available for its local AYS repo ? That would hide the complexity to the user to know about templates repository altogether.

**Comment by despiegk** [comment]
Good idea. Lets spec.
