### ISSUE TITLE
cuisine executor? does not show output while going

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#588]
![image](https://cloud.githubusercontent.com/assets/6021844/20669498/f39cfa80-b58d-11e6-9664-9bec661afc25.png)

When I start, I see no output till command is done, 
this is not ok

need to see while going.

**Comment by xmonader** [comment]
Checked on Ubuntu: works
https://gist.github.com/xmonader/ac7398c0edeae39fd16364c410e660da

Needs to be validated on osx

**Comment by abdulrahmantkhalifa** [comment]
verfied on osx
