### ISSUE TITLE
Fix Installer link in the documentation

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#593]
https://gig.gitbooks.io/jumpscale-core8/content/Installation/Installation.html

Installer link, the last one doesn't work

![screen shot 2016-11-29 at 11 33 57](https://cloud.githubusercontent.com/assets/13795109/20706486/da8f5048-b627-11e6-9788-9d2d24228e6d.png)

**Comment by yveskerwyn** [comment]
Fixed [8e45746](https://github.com/Jumpscale/jumpscale_core8/commit/8e4574637014191be134cac103a04b0942f95137)

**Comment by delandtj** [comment]
https://gig.gitbooks.io/jumpscale-core8/SAL/SAL.md -> 404 :-(

**Comment by yveskerwyn** [comment]
tx @delandtj , fixed
