### ISSUE TITLE
Failed to start Redis

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_core8#598]
After installing a fresh js8 on an Ubuntu 16.04, redis_main service was not up and running. I found the following on the logs
```
Nov 29 15:59:45 vm-3918 redis-server[23714]: *** FATAL CONFIG FILE ERROR ***
Nov 29 15:59:45 vm-3918 redis-server[23714]: Reading the configuration file, at line 78
Nov 29 15:59:45 vm-3918 redis-server[23714]: >>> 'protected-mode yes'
Nov 29 15:59:45 vm-3918 redis-server[23714]: Bad directive or wrong number of arguments
Nov 29 15:59:45 vm-3918 systemd[1]: redis_main.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 15:59:45 vm-3918 systemd[1]: redis_main.service: Unit entered failed state.
Nov 29 15:59:45 vm-3918 systemd[1]: redis_main.service: Failed with result 'exit-code'.
Nov 29 15:59:45 vm-3918 systemd[1]: redis_main.service: Service hold-off time over, scheduling restart.
Nov 29 15:59:45 vm-3918 systemd[1]: Stopped redis_main.
Nov 29 15:59:45 vm-3918 systemd[1]: redis_main.service: Start request repeated too quickly.
Nov 29 15:59:45 vm-3918 systemd[1]: Failed to start redis_main. 
```

the current redis server version that gets installed is

`Redis server v=3.0.5 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=5b64d127fd934a65`

I checked the redis manual and the 3.0 version configurations do not have the attribute "protected-mode" check https://raw.githubusercontent.com/antirez/redis/3.0/redis.conf

The module CuisineRedis gets the latest stable version of the redis server while the RdisInstaller SAL has a hardcoded configurations for the server which probably is outdated.

**Comment by rkhamis** [comment]
@ahussein did this occur on branch 8.1.0 or master?

**Comment by ahussein** [comment]
master branch

**Comment by despiegk** [comment]
Please from now test all on 810 branch
