### ISSUE TITLE
mvp-cockpit: memory leak warning

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#601]
When using the ays command you'll get the memory leaks warning:
```
/opt/jumpscale8/lib/JumpScale/data/capnp/ModelBase.py:67: UserWarning: This message has already been written once. Be very careful that you're not setting Text/Struct/List fields more than once, since that will cause memory leaks (both in memory and in the serialized data). You can disable this warning by setting the `_is_written` field of this object to False after every write.
  buff = self.dbobj.to_bytes()
```

**Comment by rkhamis** [comment]
Removing this message would be very simple.
Need to investigate we're not doing anything wrong, though.

**Comment by zaibon** [comment]
The code to remove the warning is already present (see https://github.com/Jumpscale/jumpscale_core8/commit/f9977f266ffa4388ed1d2ba9d17591679a79b8fb).
The new version of the librairies supporting this fix has been released 6 days ago (see https://github.com/jparyani/pycapnp/issues/111#issuecomment-263403373), so the message should start to dissapea as we update the lib in our build

**Comment by rkhamis** [comment]
@zaibon What with the issue Yves faced with memory, let's keep this open until we're sure it's not related.

**Comment by zaibon** [comment]
I don't have more information about that yet. so yes keep it open. this si still relevant
