### ISSUE TITLE
mvp-cockpit: document "ays run" and "ays delete"  

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#603]
https://github.com/Jumpscale/jumpscale_core8/blob/master/docs/AYS/Commands/run.md
https://github.com/Jumpscale/jumpscale_core8/blob/master/docs/AYS/Commands/delete.md

**Comment by rkhamis** [comment]
On 8.1.0, https://github.com/Jumpscale/jumpscale_core8/blob/8.1.0/docs/AYS/Commands/run.md is done.

**Comment by zaibon** [comment]
`delete` also documented in https://github.com/Jumpscale/jumpscale_core8/commit/47aa4d642e95e6925167390855cb78da53ea44f5
