### ISSUE TITLE
gogs db to capnp model import tool

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#604]
goal
- get all issues from gogs server into an issue capnp model using postgresql client

libs to change
- JumpScale.tools.issuemanager.models.IssueCollection ...
- j.clients.gogs

use
- j.data.capnp

**Comment by despiegk** [comment]
do branch 8.0.1_gogsimport
so we can review pull request

**Comment by despiegk** [comment]
https://docs.bettercoin.org/gig/cockpit_gogs_mattermost has the private info

**Comment by despiegk** [comment]
we checked the code, we need some improvements
- there are many queries today, it should be as few as possible for perf reasons
- we need to use more capnp objects, now was only one which was not optimal

**Comment by abdulrahmantkhalifa** [comment]
adjustments applied 
 - separate models  , for repo , user , and organization 
 - less query calls

**Comment by rkhamis** [comment]
Missing docs to close
