### ISSUE TITLE
AYS: Producers are not correctly auto created

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_core8#614]
Using the following blueprint and actortemplate

- [https://github.com/0-complexity/ays_automatic_cockpit_based_testing/blob/test_auto_creation/ays_testing/blueprints/test_auto_behavior.yaml](url)

- [https://github.com/0-complexity/ays_automatic_cockpit_based_testing/tree/test_auto_creation/ays_testing/actorTemplates/test_auto_behavior](url)

The same bp and service template works if the schema was changed to not use list in the sshkeys definition

the the following part of the _initProducers function from the Service.py module is the problem:
```
for i, producer_model in enumerate(actor.model.dbobj.producers):
            producer_role = producer_model.actorRole

            instances = args.get(producer_model.argKey, args.get(producer_role, ""))

            if not j.data.types.list.check(instances):
                instances = [instances]

            for i in instances:
```

when the producer is defined as a list and the service didnt exist already then the instances variable will be evaluated to [] and then the for in in instances loop will not be executed.

**Comment by rkhamis** [comment]
@xmonader can you run this test against your branch?

**Comment by rkhamis** [comment]
Runs perfectly now!
