### ISSUE TITLE
JumpScale in a box not working?

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#632]
After having installed **JumpScale in a sandbox** as documented [here](https://gig.gitbooks.io/jumpscale-core8/content/Installation/JS8.html) I was expecting that I could at least use ```js``` but I get this:

```
root@vm-45:/tmp# js
The program 'js' can be found in the following packages:
 * nodejs
 * rhino
Try: apt install <selected package>
```

Is this normal? Is this a bug? Or am I missing something?

**Comment by rkhamis** [comment]
This documentation looks out of date.
I'll put this as part of 8.1.1

**Comment by despiegk** [comment]
lets revisit, for 8.2.1 we are working on new sanbox mechanism, lets check then

**Comment by rkhamis** [comment]
jumpscale9 is immediately in a docker, right out of the box. No longer relevant
