### ISSUE TITLE
Create DDoS mitigation AYS for VDC's

### ISSUE THREAD

**Issue by hofkensj** [Jumpscale/jumpscale_core8#647]
# Feature Description
create an AYS that can be deployed in front of a VDC to prevent DDoS attacks.

DDoS at infra level (SYN / UDP flooding and repeating)
DDoS at application layer (to start, prevent HTTP request / DNS request  flooding)

# Why we need it
to be at par with AWS and Azure / both deliver this service
https://d0.awsstatic.com/whitepapers/Security/DDoS_White_Paper.pdf

# Customers / partners asking for it

# Committed dates

**Comment by despiegk** [comment]
does not belong here

**Comment by rkhamis** [comment]
Moved to https://github.com/Jumpscale/ays_jumpscale8/issues/232
