### ISSUE TITLE
Create Loadbalancer AYS

### ISSUE THREAD

**Issue by hofkensj** [Jumpscale/jumpscale_core8#648]
# Feature Description
Customers often request loadbalancing functions.  Deliver that as an AYS.  Loadbalance to different instances in a VDC or across instances in different VDCs

# Why we need it
to be at par with AWS and Azure / both deliver this service

# Customers / partners asking for it

# Committed dates

**Comment by despiegk** [comment]
in wrong repo, should not be here.
there should be ays repo on 0-complexity and put there, lets discuss
