### ISSUE TITLE
KVS on ardb

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#656]
- use https://github.com/nimscale/stor as backend
- create a KVS server in jumpscale for this
- run the tests

**Comment by rkhamis** [comment]
depends on decisions taken after examining https://github.com/Jumpscale/jumpscale_core8/issues/664

**Comment by despiegk** [comment]
Please implement on pudge.
The remarks above dont seem valid
Sophia db is a datastor like leveldb. Rockstor. ....
Need to put a network interface on top like pudge.
Pudge is memcache protocol
Should be easy job

**Comment by zaibon** [comment]
@despiegk 
I'm hitting an issue with this. 
memcached protocol doesn't have support to list keys present in the datastore. But this features is eavily use by our Key Value store interface.

I managed to find a hack on top of memcached to get the keys, but pudge doesn't implement the calls used in the hack. so I'm kinda block on this.

**Comment by zaibon** [comment]
I've been reading through the code of pudge and it actually implements the `keys` command from redis already. But since it's not a memcached command the client I use doesn't support it. I'll have to fork the memcached client and add the support for the `keys` command.
