### ISSUE TITLE
fuse example on top of new flist

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#657]
- use low level fuse impl on top of flist
   -  https://pypi.python.org/pypi/llfuse/
- create a filesystem which
    - exposes files from a chosen plist (use the metadata interface on plist)
    - allow read/write
    - files are written to ardb using https://github.com/nimscale/stor
    - for RW support while opening put on temp dir & only upload when file close or after certain period

**Comment by despiegk** [comment]
in branch 8.2.0_flist_fuse

**Comment by despiegk** [comment]
the implementation is very bad.
all is in mem as copy of capnp
this is not usable

**Comment by khaledkbadr** [comment]
@despiegk I thought it's an example to validate the usage of the `metadata layer` hence that was my main focus to validate the `metadata layer` usability.
