### ISSUE TITLE
jsagent8 is broken

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/jumpscale_core8#663]
jsagent8 is the jsagent in jumpscale8.
It still relies on j.dirs.hrdDir which does not exist anymore.
j.application.config behaves in another way then before.

**Comment by abdulrahmantkhalifa** [comment]
his is pushed on 8.1.1 if we are moving this issue to 8.2.0, then 8.1.1 not 8.1.0 
branch has to be rebased/merged  onto 8.2.0

**Comment by john-kheir** [comment]
## verified on 8.1.1
- From controller of any env (which uses js7) try to run jumpscript (ex:echo_async) on jsagent8 (which uses js8)
**cmd to run:** jsac exec -o jumpscale -n echo_async -nid 7
-o : is the organization
