### ISSUE TITLE
investigate performance of python to sophia

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#664]
Whether more performent than pudge

**Comment by zaibon** [comment]
relates to https://github.com/nimscale/stor/issues/5

**Comment by khaledkbadr** [comment]
* Using the same algorithm in `python` as in `nim`, the `nim` implementation is much faster even with the porting to python
* Second thing, `Sophia` is an embeddable database that can't be used as server, so even if we go that way we have to implement our own server/wrapper to it.
* Most `python` packages that binds to `Sophia` has problems with `python3`
