### ISSUE TITLE
path library issue

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jumpscale_core8#678]
**Description**
After installing the cockpit, I tried to run Portal service and I faced the following error
![screenshot from 2017-01-03 15-43-46](https://cloud.githubusercontent.com/assets/17981089/21609506/7e980720-d1cb-11e6-8212-e52a6b89ea85.png)

Jumscale is using path library version 9.0 and There is a new version right now.

**Comment by xmonader** [comment]
Thanks. Should be fixed after this PR #677

**Comment by john-kheir** [comment]
verified on 8.1.1
