### ISSUE TITLE
AYS daemon to respect action dependencies

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#692]
AYS Daemon walks over actions and marks the recurring ones as `scheduled` whether they're ready to be scheduled or not.
This is not the correct behavior and results in issues such as https://github.com/Jumpscale/jscockpit/issues/325

**Comment by xmonader** [comment]
should be fixed by this
https://github.com/Jumpscale/jumpscale_core8/commit/bdd4646ebc2f5841dd997570e59e56f9dbc296b6
