### ISSUE TITLE
Install ARDB in default JS installation

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#694]
AYS should work out of the box

**Comment by despiegk** [comment]
think this is wrong approach, I believe the std should be redis so we don't need an additional component & we need to fix the way how we cleanup jobs

**Comment by rkhamis** [comment]
What me and @zaibon discussed is to archive old jobs and runs. But since repos don't necessarily have a lifetime, we could potentially have an archived repo in very high demand.
This would be really slow if we had to read it from fs everytime which is why we turned to ardb - which so far isn't optimal either.

**Comment by despiegk** [comment]
no need to keep old records, no archive feature.
in ays there should be feature to remove old jobs
