### ISSUE TITLE
Get cuisine modules up to standard and all working

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#696]
Standard defined in https://github.com/Jumpscale/jumpscale_core8/issues/695

Modules are:

- [x] syncthing 
- [x] GOGs (@abdulrahmantkhalifa)
- [x] python sandbox (@despiegk and @zaibon)
- [x] rsync (@rkhamis)
- [x] btrfs (@maxux)
- [x] DNS (@ashraffouda)
- [x] Zerotier (@rkhamis)
- [x] Caddy (@xmonader)
- [ ] Owncloud (@xmonader)
- [x] Portal +js libs (@abdulrahmantkhalifa)
- [x] ssh portforward (already done by @despiegk)

**Comment by despiegk** [comment]
all on same branch 8.2.0_cuisine
