### ISSUE TITLE
autotests updated 8.2.0 cuisine on ays & docker

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#705]
![image](https://cloud.githubusercontent.com/assets/6021844/21793425/a8842caa-d70a-11e6-9305-491080c0fa9c.png)

dependencies
- cuisine clean 
- ays clean
- docker working well in ays

**Comment by rkhamis** [comment]
Very good!
I suggest we don't do it with a test method, but rather with unit/integration testing. Will add links to how we can do that cleanly and easily so we can later have a testsuite.

**Comment by rkhamis** [comment]
We have ays_build tests for that. Need to be verified on 8.2.0

**Comment by rkhamis** [comment]
@abdulrahmantkhalifa Closely coupled with https://github.com/Jumpscale/jumpscale_core8/issues/659. After fixing builds, please validate the tests all pass successfully.
