### ISSUE TITLE
potential daemon improvement for AYS daemon

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#711]
need to check if following idea's make sense

- create daemon nanomsg on top of asyncio OR capnp asyncio (is this possible?)
- keep all services efficiently in mem (no redis, ...)
- dedupe jobs/... (some smart way to only keep relevant jobs), dump to log (optionally)
- use http://www.npcole.com/npyscreen/ commandline UI on top of daemon to have command line visualization

info
- http://tim.dysinger.net/posts/2013-09-16-getting-started-with-nanomsg.html

**Comment by zaibon** [comment]
> keep all services efficiently in mem (no redis, ...)

This can't be done cause if we don't have a common datastore where we keep the service. you will have inconcistency between all the process that use AYS (portal, cockpit API, daemon)

**Comment by despiegk** [comment]
could use https://github.com/ronf/asyncssh
- forget paramiko
- no subprocesses, all are ssh sessions

all in mem can work, but then portal needs to call the daemon to get the info

daemon can expose functionality over (need to check)
- rest (goraml)
- capnp
- own proto

**Comment by rkhamis** [comment]
Current daemon works all in mem, except jobs and runs.
Investigation to offload those to disk are currently underway here: https://github.com/Jumpscale/jumpscale_core8/issues/797
