### ISSUE TITLE
Redis cuisine is incomplete.

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/jumpscale_core8#719]
The install method http://github.com/jumpscale/jumpscale_core8/blob/8.1.1/lib/JumpScale/tools/cuisine/apps/CuisineRedis.py#L67

Is incomplete and useless.

**Comment by rkhamis** [comment]
Already fixed on 8.2.0.
In 8.1.1, I'd rather not do any development not related to the release. Please use the build instead of install.
