### ISSUE TITLE
validate AYS

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#773]
create bugs for everything regarding AYS
 - missing docs
 - start
 - usability
 - performance ...

**Comment by rkhamis** [comment]
Also, run testsuite when done: https://github.com/Jumpscale/jumpscale_core8/tree/8.2.0/tests

**Comment by alichaddad** [comment]
Waiting for the updated test suites to complete the testing.

**Comment by rkhamis** [comment]
@ahussein migrating the testsuite

**Comment by ahussein** [comment]
AYS tests results after running on 8.2.0 js can be found in the attached file 
[Driver.txt](https://github.com/Jumpscale/jumpscale_core8/files/913799/Driver.txt)

Need to fix the failures!

**Comment by ahussein** [comment]
All tests are migrated except:

- js8_install_test.yaml
- test_timeout_actions.yaml
- test_validate_service_args.yaml

They need to be reviewed by their authors.

**Comment by ahussein** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/863
https://github.com/Jumpscale/ays_jumpscale8/pull/223

**Comment by ahussein** [comment]
new PRs after reviewing the rest of the tests
https://github.com/Jumpscale/ays_jumpscale8/pull/226
https://github.com/Jumpscale/jumpscale_core8/pull/876
