### ISSUE TITLE
No error messages when executing blueprints

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/jumpscale_core8#782]
Executing blueprints that contains errors(unknown templates, key error,..) produces same message when the blueprint is successfully executed:

```
blueprint b.yaml executed
```
Seeing the error messages is only possible via the server logs.

Should return something like the errors in the server logs:
```
- ERROR    - Service template test_validate_ays_update not found. Can't execute this blueprint
```

**Comment by rkhamis** [comment]
Fixed in https://github.com/Jumpscale/jumpscale_core8/commit/5836f88165fb70378b9c3bdf08e9e2f32e6694b1 and https://github.com/Jumpscale/jumpscale_core8/commit/905dd950b25534d1ce027585699023acf7b22b08
