### ISSUE TITLE
Jumpscripts compatibility problem 

### ISSUE THREAD

**Issue by mie00** [Jumpscale/jumpscale_core8#80]
Some jumpscripts under [apps/agentcontroller/jumpscripts/jumpscale](https://github.com/Jumpscale/jumpscale_core8/tree/master/apps/agentcontroller/jumpscripts/jumpscale) fail at the agentcontroller. because either they are not compatible with python3 or they use a module that is not installed `psutil`.

**Comment by despiegk** [comment]
@robvanmieghem is this ok to close?
what needs to be done to verify

**Comment by robvanmieghem** [comment]
@mie00

> is this ok to close?
what needs to be done to verify

**Comment by mie00** [comment]
Yes, It is ok to close.
Adding them to a running controller without an exception is enough to verify.
