### ISSUE TITLE
Include config files inside the service template

### ISSUE THREAD

**Issue by mie00** [Jumpscale/jumpscale_core8#800]
It would be cleaner to be able to include certain files inside the service template directory, something like a configuration file. A lot cleaner than including them as a string in the actions.py file directly.

**Comment by zaibon** [comment]
You should not have config file in a string in the actions.py file.
The flist should contain default configuration and the install action of the service will properly update that config file when required.

**Comment by mie00** [comment]
Yes, you are right. The service templates should only contain the instructions to do an action (installation, starting, etc.) as it is only used for management. But the real data should be fetched from somewhere else.
closing..
