### ISSUE TITLE
Validate jumpscale on g8os containers

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#807]
Test installation and ays. Maybe a few cuisine modules.

**Comment by ashraffouda** [comment]
g8os is not ready yet.
1- installed g8os docker image 
2- I created a container and found it has a problem using apt-get on it, and the g8ufs is not up-to-date

**Comment by ashraffouda** [comment]
tested again 
https://github.com/g8os/core0/issues/190

**Comment by zaibon** [comment]
you should not use the docker image. this is most probably outdated. Check the doc how to boot a proper vm or packet.net
