### ISSUE TITLE
GeoDNS Cuisine module

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jumpscale_core8#82]
Write a cuisine module to deal with https://github.com/abh/geodns

requirements :
- install
- start
- stop
- methods to deal with basic DNS operations (Records A, CNAME, ...)

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/89

**Comment by despiegk** [comment]
we should write some tests for it

**Comment by abdulrahmantkhalifa** [comment]
what kind of tests is required , unit test, or just test that it runs, connects, and resolves the requests

**Comment by despiegk** [comment]
Yes indeed
2nd

Some examples how to use
Put documentation

On Sunday, 13 March 2016, abdulrahmantkhalifa <notifications@github.com>
wrote:

> what kind of tests is required , unit test, or just test that it runs,
> connects, and resolves the requests
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/jumpscale_core8/issues/82#issuecomment-195961088>
> .
>


-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/Jumpscale/jumpscale_core8/commit/6dae09587e8ba71d884bfc8b2dba54c39ed5ce97

**Comment by abdulrahmantkhalifa** [comment]
#106 , if need the file to be hooked into jumpscale please inform
