### ISSUE TITLE
Pop cached value of updated schemas

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#824]
Schemas are cached [here](https://github.com/Jumpscale/jumpscale_core8/blob/8.2.0/lib/JumpScale/data/capnp/Capnp.py#L101) and as such, updating the schema will not return the updated value.

Make sure that when loading an updated schema to pop the corresponding cached value in order to get reloaded

**Comment by xmonader** [comment]
After spending sometime tracing the issue, problem is `having the same schema id` for 2 different actors.

updating the cached schema would break the first repository. 
The user shouldn't have different actors with the same schema ID

**Comment by zaibon** [comment]
> The user shouldn't have different actors with the same schema ID

Exactly and this is also cleary specified in the specs of Capnp. Also any change in the schema implies a new ID.
