### ISSUE TITLE
cloning during installation asks to verify github's authenticity

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#826]
```
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by ashraffouda** [comment]
I tested the installation and this issue didn't happen

**Comment by islamTaha12** [comment]
it stills exist with any vms
![screenshot from 2017-04-13 11-26-42](https://cloud.githubusercontent.com/assets/17981089/24999290/9ed5b122-2045-11e7-8004-dc05e13b7adb.png)

**Comment by ashraffouda** [comment]
are you installing by doing bash install.sh or using a blueprint?

**Comment by islamTaha12** [comment]
I do 
```bash
cd /tmp && export JSBRANCH="8.2.0" && curl -k https://raw.githubusercontent.com/Jumpscale/jumpscale_core8/$JSBRANCH/install/install.sh?$RANDOM > install.sh && bash install.sh
```

**Comment by ashraffouda** [comment]
Added a fix to ensure github is already added before installation for those machines that have the issue 
https://github.com/Jumpscale/jumpscale_core8/commit/c1ba70d6c7d8afdf4f25b747f79a470c0cd05711
