### ISSUE TITLE
[AYS] serviceGet will return None even if multiple services found

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_core8#841]
Scenario:  a repo that contains the following services
```
In [26]: repo.services
Out[26]:
[service:sshkey!auto_0,
 service:test_auto_behavior2!2min,
 service:test_auto_behavior!auto_parent,
 service:sshkey!auto_1,
 service:test_auto_behavior!0min,
 service:vdcfarm!auto_4,
 service:test_auto_behavior!2min]

```
if we try to get the service test_auto_behavior!2min it will return None

```
In [29]: repo.serviceGet(role='test_auto_behavior', instance='2min') is None
Out[29]: True
```

tracing back the code, the method serviceGet code will find two services [test_auto_behavior!2min, test_auto_behavior2!2min] and then will return None since it expect only one service to be returned.

This behavior is causing problems with the testsuite

**Comment by rkhamis** [comment]
`[test_auto_behavior!2min, test_auto_behavior2!2min]` do not have the same role.
"test_auto_behavior2" shouldn't have been in the result set in the first place.
