### ISSUE TITLE
Installation Issues -- Missing requirements ?

### ISSUE THREAD

**Issue by rainmanh** [Jumpscale/jumpscale_core8#850]
Hi,

I have followed the installation process but ...
After installing mongodb and portal I got a number of issues at the portal start up as it seems a number of python modules are missing.

Modules : 
 *  getenv 
 *  beaker 
 *  gitlab3
 *  jinja2
 *  mimeparse
 * flask
 * Flask-Bootstrap
 * mongoengine
 * tornado

Are missing. That should be part of the base requirements.

After installing the relevant modules using  the default versions as provided by pip...

Portal service:

```
(JS8) # systemctl start portal.service
(JS8)# systemctl status portal.service
● portal.service - portal
   Loaded: loaded (/etc/systemd/system/portal.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-04-24 18:41:14 BST; 231ms ago
 Main PID: 21322 (python3.5)
    Tasks: 2
   Memory: 20.8M
      CPU: 232ms
   CGroup: /system.slice/portal.service
           └─21322 python3.5 -q portal_start.py

Apr 24 18:41:14 VDisks-OVS-Testing systemd[1]: Started portal.
```
Now it seems to work.

Many thanks

**Comment by xmonader** [comment]
Not an issue. You need to use `installDeps` method
https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/tools/cuisine/development/CuisineJS8.py#L49

Thank you.

**Comment by rainmanh** [comment]
I didn't manage to find that piece of information.
Perfect @xmonader . 
Thanks for the information.
