### ISSUE TITLE
Recurring action lost after updating jumpscale and grid ays templates

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/jumpscale_core8#872]
The recurring bootstrap action was lost after I updated my env

**Comment by xmonader** [comment]
Well, updated recurring actions get picked up by the ays server through `ays actors update`.

**Comment by xmonader** [comment]
Fixed by https://github.com/Jumpscale/jumpscale_core8/commit/849a9c124a243d27dbacd76fcf23ccb194b73d4f
