### ISSUE TITLE
flist-merger: file permissions are not set properly and symlinks get duplicated (cross g8os/hub #9)

### ISSUE THREAD

**Issue by maxux** [Jumpscale/jumpscale_core8#881]
As commented here, flist merger seems to provide weird results: https://github.com/g8os/hub/issues/9#issuecomment-298360190

The flist merge code used is:
https://github.com/g8os/hub/blob/1.1.0-alpha/python/flist-uploader.py#L161

**Comment by ahussein** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/894
