### ISSUE TITLE
AYS server does not want to die, which means that eventloops are stuck.

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/jumpscale_core8#916]
### Installation information

- jumpscale version: 8.2.0 (dfd1f642098fdb7d611386380b463aa94378a356)
- operating system: Ubuntu 16.04

### Detailed description
![afbeelding](https://cloud.githubusercontent.com/assets/15246294/26263249/4945a118-3cd8-11e7-8d2f-05e6dfb8ee37.png)

Pressing CTRL-c eventually did not work nor did send SIG_TERM. Needed to send SIG_KILL to be able to end the process.

### Steps to reproduce
Install a resourcepool on be-g8-3.
Try to deploy a storagecluster [(won't work due to other bug in ays)](https://github.com/Jumpscale/jumpscale_core8/issues/915)
Then wait for 6 hours.

**Comment by rkhamis** [comment]
Should be fixed in https://github.com/Jumpscale/jumpscale_core8/pull/923
