### ISSUE TITLE
Ays search for ays repos returns false positive

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/jumpscale_core8#920]
### Installation information

- jumpscale version: 8.2.0
- operating system: Ubuntu

### Detailed description
This regex https://github.com/Jumpscale/jumpscale_core8/blob/8.2.0/lib/JumpScale/baselib/atyourservice81/lib/TemplateRepo.py#L16 script, returns `rogerthat_tests/mobicage/utils/test_transactions.py`

**Comment by ahussein** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/927

**Comment by rkhamis** [comment]
same fix needs to be applied here: https://github.com/Jumpscale/jumpscale_core8/blob/8.2.0/lib/JumpScale/baselib/atyourservice81/lib/AtYourServiceRepo.py#L92
