### ISSUE TITLE
Error in service should NOT crash AYS server

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core8#926]
See https://gist.github.com/grimpy/0af462d0859ec03c50ac1c21a5815e1c

**Comment by zaibon** [comment]
From the logs I see that it's not only ays server that is stopped but the all process with a nice `   sys.exit(1)`...
I though we removed this non-sense already

**Comment by rkhamis** [comment]
@zaibon looks like it's the errorconditionhandler.... we should be using j.exceptions in all cases, no?

**Comment by zaibon** [comment]
We don't even raise, we just convert a python exception into an eco object. At least that's what I wanted to do when I wrote these line.
I have no idea why this method even try to do more then just creating the eco object.

**Comment by xmonader** [comment]
https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/core/errorhandling/ErrorConditionHandler.py#L157

We check against instances of `Exception` not `BaseException` which maybe the case for typchk?

**Comment by zaibon** [comment]
shoudln't we still at least raise the exception in https://github.com/Jumpscale/jumpscale_core8/commit/0f486db18e6876a28aad20a354d8ae2ad4cba064 ?

**Comment by xmonader** [comment]
@zaibon I agree, raising ValueError https://github.com/Jumpscale/jumpscale_core8/commit/8fd47635a42473513413fcebfad481f396ab4c1a
